
name: "Test Go Client v3"

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  test:
    runs-on: "ubuntu-latest"
    env:
      GOPATH: "${{ github.workspace }}"
      GO111MODULE: "off"
    defaults:
      run:
        working-directory: "${{ env.GOPATH }}/src/github.com/${{ github.repository }}"
    steps:
      - name: "Install Dependencies"
        run: "sudo apt update && sudo apt install -y openjdk-8-jdk-headless maven"

      - name: "Download and Start Hazelcast Remote Controller"
        run: "bash ./start-rc.sh &"

      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        with:
          path: "${{ env.GOPATH }}/src/github.com/${{ github.repository }}"

      - name: "Set up Go"
        uses: "actions/setup-go@v2"
        with:
          go-version: "1.15"

      - name: "Test"
        run: "bash ./local-test.sh"
